"""
ComfyUI-Gemini-Hub Nodes Package

This package contains all the Gemini AI nodes for ComfyUI integration.
"""

from .gemini_text_to_speech_node import NODE_CLASS_MAPPINGS as TTS_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TTS_NODE_DISPLAY_NAME_MAPPINGS
from .gemini_speech_to_text_node import NODE_CLASS_MAPPINGS as STT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STT_NODE_DISPLAY_NAME_MAPPINGS
from .gemini_chat_node import NODE_CLASS_MAPPINGS as CHAT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CHAT_NODE_DISPLAY_NAME_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **TTS_NODE_CLASS_MAPPINGS,
    **STT_NODE_CLASS_MAPPINGS,
    **CHAT_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TTS_NODE_DISPLAY_NAME_MAPPINGS,
    **STT_NODE_DISPLAY_NAME_MAPPINGS,
    **CHAT_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
